import type { BusinessCaseDraft, SolutionDesign, Triage } from "./types";
import { computeRoi, formatGBP, toNumber } from "./roi";

const FIELD_ORDER: Array<[keyof BusinessCaseDraft, string]> = [
  ["bottleneck", "Bottleneck"],
  ["systems_involved", "Systems involved"],
  ["hours_per_week", "Hours / week lost"],
  ["people_affected", "People affected"],
  ["target_solution", "Proposed solution"],
  ["complexity", "Complexity"],
  ["strategic_alignment", "Strategic alignment"],
];

function renderValue(value: unknown): string {
  if (Array.isArray(value)) return value.join(", ");
  if (value === null || value === undefined) return "—";
  return String(value);
}

/**
 * Render a finalised (or in-progress) business case as a formal Markdown
 * document an employee can paste into a ticket, email, or wiki.
 */
export function businessCaseToMarkdown(
  draft: BusinessCaseDraft,
  opts: { hourlyRate?: number; generatedAt?: Date } = {},
): string {
  const roi = computeRoi({
    hoursPerWeek: toNumber(draft.hours_per_week),
    peopleAffected: toNumber(draft.people_affected),
    hourlyRate: opts.hourlyRate,
  });
  const date = (opts.generatedAt ?? new Date()).toISOString().slice(0, 10);

  const lines: string[] = [
    "# Business Case — Workflow Automation",
    "",
    `*Generated by Capital AI Idea Generation on ${date}*`,
    "",
    "## Summary",
    "",
  ];

  for (const [key, label] of FIELD_ORDER) {
    const value = draft[key];
    if (value !== undefined && value !== null && value !== "") {
      lines.push(`- **${label}:** ${renderValue(value)}`);
    }
  }

  // Only include a quantified ROI section if we have an hours figure to stand on.
  if (roi.weeklyHours > 0) {
    lines.push(
      "",
      "## Quantified ROI",
      "",
      `- **Hours saved / week:** ${roi.weeklyHours}`,
      `- **Hours saved / month:** ${roi.monthlyHours}`,
      `- **Hours saved / year:** ${roi.yearlyHours}`,
      `- **Estimated annual saving:** ${formatGBP(roi.yearlyCostGBP)} ` +
        `*(at an assumed ${formatGBP(roi.rateUsed)}/hr loaded rate)*`,
    );
  }

  return lines.join("\n") + "\n";
}

/** Pretty-printed JSON snapshot of the raw business case draft. */
export function businessCaseToJson(draft: BusinessCaseDraft): string {
  return JSON.stringify(draft, null, 2) + "\n";
}

/** Render the full discovery conversation as a readable Markdown transcript. */
export function transcriptToMarkdown(
  messages: Array<{ role: "user" | "assistant"; content: string }>,
  opts: { generatedAt?: Date } = {},
): string {
  const date = (opts.generatedAt ?? new Date()).toISOString().slice(0, 10);
  const lines = ["# Capital AI — Discovery Transcript", "", `*${date}*`, ""];
  for (const m of messages) {
    const who = m.role === "assistant" ? "**Capital AI:**" : "**You:**";
    lines.push(`${who} ${m.content}`, "");
  }
  return lines.join("\n").trimEnd() + "\n";
}

/** Render the proposed solution design as a Markdown section. */
export function solutionDesignToMarkdown(sd: SolutionDesign): string {
  const lines: string[] = ["## Proposed Solution Design", ""];
  if (sd.summary) lines.push(sd.summary, "");
  if (sd.problem_addressed) lines.push(`**Problem addressed:** ${sd.problem_addressed}`, "");
  if (sd.components?.length) {
    lines.push("**Architecture**", "");
    for (const c of sd.components) lines.push(`- **${c.name}** — ${c.role}`);
    lines.push("");
  }
  if (sd.data_flow?.length) {
    lines.push("**Data / process flow**", "");
    sd.data_flow.forEach((step, i) => lines.push(`${i + 1}. ${step}`));
    lines.push("");
  }
  if (sd.tech_stack?.length) lines.push(`**Tech stack:** ${sd.tech_stack.join(", ")}`, "");
  if (sd.phases?.length) {
    lines.push("**Delivery phases**", "");
    for (const p of sd.phases) lines.push(`- **${p.name}:** ${p.detail}`);
    lines.push("");
  }
  if (sd.effort_estimate) lines.push(`**Effort:** ${sd.effort_estimate}`, "");
  if (sd.key_risks?.length) {
    lines.push("**Key risks**", "");
    for (const r of sd.key_risks) lines.push(`- ${r}`);
    lines.push("");
  }
  if (sd.success_metrics?.length) {
    lines.push("**Success metrics**", "");
    for (const m of sd.success_metrics) lines.push(`- ${m}`);
    lines.push("");
  }
  return lines.join("\n").trimEnd() + "\n";
}

/**
 * The full export pack: business case + (when present) the proposed solution
 * design, as a single Markdown document.
 */
export function exportPackToMarkdown(
  draft: BusinessCaseDraft,
  solution: SolutionDesign | null,
  opts: { hourlyRate?: number; generatedAt?: Date; triage?: Triage | null } = {},
): string {
  let out = businessCaseToMarkdown(draft, opts);
  const t = opts.triage;
  if (t && t.recommendation) {
    const rec = t.recommendation.replace(/_/g, " ");
    out +=
      `\n## Feasibility triage\n\n` +
      `- **Recommendation:** ${rec}\n` +
      (t.benefit ? `- **Benefit:** ${t.benefit}\n` : "") +
      (t.effort ? `- **Effort:** ${t.effort}\n` : "") +
      (t.data_readiness ? `- **Data readiness:** ${t.data_readiness}\n` : "") +
      (t.confidence ? `- **Confidence:** ${t.confidence}\n` : "") +
      (t.rationale ? `- **Rationale:** ${t.rationale}\n` : "");
  }
  if (solution && Object.keys(solution).length > 0) {
    out += "\n" + solutionDesignToMarkdown(solution);
  }
  return out;
}
