import type { BusinessCaseDraft } from "./types";
import { computeRoi, formatGBP, toNumber } from "./roi";

const FIELD_ORDER: Array<[keyof BusinessCaseDraft, string]> = [
  ["bottleneck", "Bottleneck"],
  ["systems_involved", "Systems involved"],
  ["hours_per_week", "Hours / week lost"],
  ["people_affected", "People affected"],
  ["target_solution", "Proposed solution"],
  ["complexity", "Complexity"],
  ["strategic_alignment", "Strategic alignment"],
];

function renderValue(value: unknown): string {
  if (Array.isArray(value)) return value.join(", ");
  if (value === null || value === undefined) return "—";
  return String(value);
}

/**
 * Render a finalised (or in-progress) business case as a formal Markdown
 * document an employee can paste into a ticket, email, or wiki.
 */
export function businessCaseToMarkdown(
  draft: BusinessCaseDraft,
  opts: { hourlyRate?: number; generatedAt?: Date } = {},
): string {
  const roi = computeRoi({
    hoursPerWeek: toNumber(draft.hours_per_week),
    peopleAffected: toNumber(draft.people_affected),
    hourlyRate: opts.hourlyRate,
  });
  const date = (opts.generatedAt ?? new Date()).toISOString().slice(0, 10);

  const lines: string[] = [
    "# Business Case — Workflow Automation",
    "",
    `*Generated by ST-Streamline on ${date}*`,
    "",
    "## Summary",
    "",
  ];

  for (const [key, label] of FIELD_ORDER) {
    const value = draft[key];
    if (value !== undefined && value !== null && value !== "") {
      lines.push(`- **${label}:** ${renderValue(value)}`);
    }
  }

  // Only include a quantified ROI section if we have an hours figure to stand on.
  if (roi.weeklyHours > 0) {
    lines.push(
      "",
      "## Quantified ROI",
      "",
      `- **Hours saved / week:** ${roi.weeklyHours}`,
      `- **Hours saved / month:** ${roi.monthlyHours}`,
      `- **Hours saved / year:** ${roi.yearlyHours}`,
      `- **Estimated annual saving:** ${formatGBP(roi.yearlyCostGBP)} ` +
        `*(at an assumed ${formatGBP(roi.rateUsed)}/hr loaded rate)*`,
    );
  }

  return lines.join("\n") + "\n";
}

/** Pretty-printed JSON snapshot of the raw business case draft. */
export function businessCaseToJson(draft: BusinessCaseDraft): string {
  return JSON.stringify(draft, null, 2) + "\n";
}

/** Render the full discovery conversation as a readable Markdown transcript. */
export function transcriptToMarkdown(
  messages: Array<{ role: "user" | "assistant"; content: string }>,
  opts: { generatedAt?: Date } = {},
): string {
  const date = (opts.generatedAt ?? new Date()).toISOString().slice(0, 10);
  const lines = ["# ST-Streamline — Discovery Transcript", "", `*${date}*`, ""];
  for (const m of messages) {
    const who = m.role === "assistant" ? "**ST-Streamline:**" : "**You:**";
    lines.push(`${who} ${m.content}`, "");
  }
  return lines.join("\n").trimEnd() + "\n";
}
