import { test } from "node:test";
import assert from "node:assert/strict";
import {
  businessCaseToMarkdown,
  businessCaseToJson,
  transcriptToMarkdown,
  exportPackToMarkdown,
} from "../src/lib/business-case";
import type { BusinessCaseDraft, SolutionDesign } from "../src/lib/types";

test("export pack combines the business case and the solution design", () => {
  const draft: BusinessCaseDraft = { bottleneck: "Manual re-keying", hours_per_week: 5, people_affected: 4 };
  const solution: SolutionDesign = {
    summary: "Event-driven Power Automate ingestion",
    components: [{ name: "Power Automate", role: "ingest + validate", kind: "process" }],
    data_flow: ["Returns arrive", "Validated and written to the dashboard"],
    tech_stack: ["Power Automate", "SAP"],
    key_risks: ["Source data quality"],
  };
  const md = exportPackToMarkdown(draft, solution, { generatedAt: new Date("2026-06-06") });
  assert.match(md, /# Business Case/);
  assert.match(md, /## Proposed Solution Design/);
  assert.match(md, /Event-driven Power Automate ingestion/);
  assert.match(md, /Validated and written to the dashboard/);
});

test("export pack omits the solution section when there's no design", () => {
  const draft: BusinessCaseDraft = { bottleneck: "x" };
  const md = exportPackToMarkdown(draft, null);
  assert.match(md, /# Business Case/);
  assert.ok(!md.includes("Proposed Solution Design"));
});

const DRAFT: BusinessCaseDraft = {
  bottleneck: "Manual re-formatting of contractor Excel spreadsheets.",
  systems_involved: ["Excel", "PowerBI"],
  hours_per_week: 3,
  people_affected: 4,
  target_solution: "Power Automate Shared Drive Integration Flow",
  complexity: "Medium",
  strategic_alignment: "Capital Program Efficiency Target",
};

test("markdown includes a title and the key fields", () => {
  const md = businessCaseToMarkdown(DRAFT, { generatedAt: new Date("2026-06-03") });
  assert.match(md, /# Business Case/);
  assert.match(md, /Generated by Capital AI Idea Generation on 2026-06-03/);
  assert.match(md, /\*\*Bottleneck:\*\* Manual re-formatting/);
  assert.match(md, /\*\*Systems involved:\*\* Excel, PowerBI/);
  assert.match(md, /\*\*Proposed solution:\*\* Power Automate/);
});

test("markdown quantifies ROI from hours and people", () => {
  const md = businessCaseToMarkdown(DRAFT, { hourlyRate: 40 });
  // 3 hrs * 4 people = 12/wk, 48/wk*... -> 12*4=48 monthly? weekly 12, monthly 48, yearly 576
  assert.match(md, /Hours saved \/ week:\*\* 12/);
  assert.match(md, /Hours saved \/ month:\*\* 48/);
  assert.match(md, /Hours saved \/ year:\*\* 576/);
  assert.match(md, /Estimated annual saving:\*\* £23,040/); // 576 * 40
});

test("markdown omits the ROI section when there are no hours", () => {
  const md = businessCaseToMarkdown({ bottleneck: "Something vague" });
  assert.doesNotMatch(md, /Quantified ROI/);
});

test("json export is pretty-printed and round-trips", () => {
  const json = businessCaseToJson(DRAFT);
  assert.deepEqual(JSON.parse(json), DRAFT);
  assert.match(json, /\n {2}"bottleneck"/);
});

test("transcript renders each turn with a speaker label", () => {
  const md = transcriptToMarkdown(
    [
      { role: "assistant", content: "What's your role?" },
      { role: "user", content: "Project controls." },
    ],
    { generatedAt: new Date("2026-06-03") },
  );
  assert.match(md, /# Capital AI — Discovery Transcript/);
  assert.match(md, /\*\*Capital AI:\*\* What's your role\?/);
  assert.match(md, /\*\*You:\*\* Project controls\./);
});
