import { test } from "node:test";
import assert from "node:assert/strict";
import {
  businessCaseToMarkdown,
  businessCaseToJson,
  transcriptToMarkdown,
} from "../src/lib/business-case";
import type { BusinessCaseDraft } from "../src/lib/types";

const DRAFT: BusinessCaseDraft = {
  bottleneck: "Manual re-formatting of contractor Excel spreadsheets.",
  systems_involved: ["Excel", "PowerBI"],
  hours_per_week: 3,
  people_affected: 4,
  target_solution: "Power Automate Shared Drive Integration Flow",
  complexity: "Medium",
  strategic_alignment: "Capital Program Efficiency Target",
};

test("markdown includes a title and the key fields", () => {
  const md = businessCaseToMarkdown(DRAFT, { generatedAt: new Date("2026-06-03") });
  assert.match(md, /# Business Case/);
  assert.match(md, /Generated by ST-Streamline on 2026-06-03/);
  assert.match(md, /\*\*Bottleneck:\*\* Manual re-formatting/);
  assert.match(md, /\*\*Systems involved:\*\* Excel, PowerBI/);
  assert.match(md, /\*\*Proposed solution:\*\* Power Automate/);
});

test("markdown quantifies ROI from hours and people", () => {
  const md = businessCaseToMarkdown(DRAFT, { hourlyRate: 40 });
  // 3 hrs * 4 people = 12/wk, 48/wk*... -> 12*4=48 monthly? weekly 12, monthly 48, yearly 576
  assert.match(md, /Hours saved \/ week:\*\* 12/);
  assert.match(md, /Hours saved \/ month:\*\* 48/);
  assert.match(md, /Hours saved \/ year:\*\* 576/);
  assert.match(md, /Estimated annual saving:\*\* £23,040/); // 576 * 40
});

test("markdown omits the ROI section when there are no hours", () => {
  const md = businessCaseToMarkdown({ bottleneck: "Something vague" });
  assert.doesNotMatch(md, /Quantified ROI/);
});

test("json export is pretty-printed and round-trips", () => {
  const json = businessCaseToJson(DRAFT);
  assert.deepEqual(JSON.parse(json), DRAFT);
  assert.match(json, /\n {2}"bottleneck"/);
});

test("transcript renders each turn with a speaker label", () => {
  const md = transcriptToMarkdown(
    [
      { role: "assistant", content: "What's your role?" },
      { role: "user", content: "Project controls." },
    ],
    { generatedAt: new Date("2026-06-03") },
  );
  assert.match(md, /# ST-Streamline — Discovery Transcript/);
  assert.match(md, /\*\*ST-Streamline:\*\* What's your role\?/);
  assert.match(md, /\*\*You:\*\* Project controls\./);
});
